name: Basketball Stats App Daily Data Update

on:
#  schedule:
#    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-scrapers:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for git pull --rebase to work reliably

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true # Uses fast, pre-compiled binaries instead of compiling from source

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev

      - name: Install R Libraries
        run: |
          Rscript -e 'install.packages(c("dplyr", "purrr", "tidyr", "stringr", "stringi", "httr", "jsonlite", "glue", "janitor", "lubridate", "rvest", "readr", "xml2", "vroom"))'

      - name: Pro A Scraper
        continue-on-error: true
        run: Rscript bball-stats/scrapers/FR-scraper.R

      - name: Serie A Scraper
        continue-on-error: true
        run: Rscript bball-stats/scrapers/IT-scraper.R

      - name: BBL Scraper
        continue-on-error: true
        run: Rscript bball-stats/scrapers/DE-scraper.R

      - name: GBL Scraper
        continue-on-error: true
        run: Rscript bball-stats/scrapers/GR-scraper.R

      - name: ACB Scraper
        continue-on-error: true
        run: Rscript bball-stats/scrapers/ES-scraper.R

      - name: TBSL Scraper
        continue-on-error: true
        run: Rscript bball-stats/scrapers/TR-scraper.R

      # - name: NBB Scraper # run this locally, 403 error :(

      - name: Euroleague Scraper
        continue-on-error: true
        run: Rscript bball-stats/scrapers/EL-scraper.R

      - name: Eurocup Scraper
        continue-on-error: true
        run: Rscript bball-stats/scrapers/EC-scraper.R

      - name: Debug - List Files
        run: |
          echo "Files in root:"
          ls -l *.csv || echo "No CSVs in root"
          echo "Files in data folder:"
          ls -R bball-stats/data/

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Updated data on: $(date +'%Y-%m-%d')" || exit 0
          git pull --rebase origin main
          git push origin main
